<?php
/**
 * Created by PhpStorm.
 * Author: Wai Yan Aung
 * Date: 9/29/2016
 * Time: 2:11 PM
 */

use Illuminate\Database\Seeder;

class Default_InvestigationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('investigations')->delete();

        $tempArrays = array(
            ['id'=>'1','name'=>'CP (Auto-33 para)','group_name'=>'Haematology1','price'=>'1000','description'=>''],
            ['id'=>'2','name'=>'CP (Manual)','group_name'=>'Haematology1','price'=>'1000','description'=>''],
            ['id'=>'3','name'=>'Reticulocyte Count (Auto)','group_name'=>'Haematology1','price'=>'1000','description'=>''],
            ['id'=>'4','name'=>'ABO/RhGrouping & Matching','group_name'=>'Haematology2','price'=>'1000','description'=>''],
            ['id'=>'5','name'=>'Coomb"s Test','group_name'=>'Haematology2','price'=>'1000','description'=>''],
            ['id'=>'6','name'=>'Prothrombin Time (PT/INR)','group_name'=>'Coagulation_Profile','price'=>'1000','description'=>''],
            ['id'=>'7','name'=>'Activated Partial Thromboplastin Time(APTT)','group_name'=>'Coagulation_Profile','price'=>'1000','description'=>''],
            ['id'=>'8','name'=>'Hb%','group_name'=>'Haematology1','price'=>'1000','description'=>''],
            ['id'=>'9','name'=>'ESR','group_name'=>'Haematology1','price'=>'1000','description'=>''],
            ['id'=>'10','name'=>'PCV','group_name'=>'Haematology1','price'=>'1000','description'=>''],
            ['id'=>'11','name'=>'Platelet','group_name'=>'Haematology1','price'=>'1000','description'=>''],
            ['id'=>'12','name'=>'G6PD(Screening)','group_name'=>'Haematology1','price'=>'1000','description'=>''],
            ['id'=>'13','name'=>'ABO Grouping','group_name'=>'Haematology1','price'=>'1000','description'=>''],
            ['id'=>'14','name'=>'Rh','group_name'=>'Haematology1','price'=>'1000','description'=>''],
            ['id'=>'15','name'=>'Hb Electrophoresis','group_name'=>'Haematology1','price'=>'1000','description'=>''],
            ['id'=>'16','name'=>'Hb F(Singer"s Test)','group_name'=>'Haematology1','price'=>'1000','description'=>''],
            ['id'=>'17','name'=>'CD4 Count','group_name'=>'Haematology1','price'=>'1000','description'=>''],
            ['id'=>'18','name'=>'HbA1C','group_name'=>'Haematology1','price'=>'1000','description'=>''],
            ['id'=>'19','name'=>'G6PD(Q)','group_name'=>'Haematology1','price'=>'1000','description'=>''],
            ['id'=>'20','name'=>'Clod/Warm Agglutination','group_name'=>'Haematology2','price'=>'1000','description'=>''],
            ['id'=>'21','name'=>'Fibrinogen','group_name'=>'Coagulation_Profile','price'=>'1000','description'=>''],
            ['id'=>'22','name'=>'Favtor VIII','group_name'=>'Coagulation_Profile','price'=>'1000','description'=>''],
            ['id'=>'23','name'=>'Factor IX','group_name'=>'Coagulation_Profile','price'=>'1000','description'=>''],
            ['id'=>'24','name'=>'D-Dimer','group_name'=>'Coagulation_Profile','price'=>'1000','description'=>''],
            ['id'=>'25','name'=>'Von Willebrand Factor','group_name'=>'Coagulation_Profile','price'=>'1000','description'=>''],
            ['id'=>'26','name'=>'FDP','group_name'=>'Coagulation_Profile','price'=>'1000','description'=>''],
            ['id'=>'27','name'=>'Ferritin','group_name'=>'Iron_Study','price'=>'1000','description'=>''],
            ['id'=>'28','name'=>'Serum iron','group_name'=>'Iron_Study','price'=>'1000','description'=>''],
            ['id'=>'29','name'=>'TIBC','group_name'=>'Iron_Study','price'=>'1000','description'=>''],
            ['id'=>'30','name'=>'Lipid Profile(F/R)','group_name'=>'Biochemistry','price'=>'1000','description'=>''],
            ['id'=>'31','name'=>'Total Cholesterol','group_name'=>'Biochemistry','price'=>'1000','description'=>''],
            ['id'=>'32','name'=>'Triglyceride','group_name'=>'Biochemistry','price'=>'1000','description'=>''],
            ['id'=>'33','name'=>'HDL','group_name'=>'Biochemistry','price'=>'1000','description'=>''],
            ['id'=>'34','name'=>'LDL','group_name'=>'Biochemistry','price'=>'1000','description'=>''],
            ['id'=>'35','name'=>'Bilirubin (Total/Direct)','group_name'=>'Liver_Function_Tests','price'=>'1000','description'=>''],
            ['id'=>'36','name'=>'ALT/SGPT','group_name'=>'Liver_Function_Tests','price'=>'1000','description'=>''],
            ['id'=>'37','name'=>'Alkaline Phosphatase','group_name'=>'Liver_Function_Tests','price'=>'1000','description'=>''],
            ['id'=>'38','name'=>'Gamma_GT','group_name'=>'Liver_Function_Tests','price'=>'1000','description'=>''],
            ['id'=>'39','name'=>'AST [Aspartate Transaminase]','group_name'=>'Cardiac_Enzymes','price'=>'1000','description'=>''],
            ['id'=>'40','name'=>'LDH [Lactate Dehydrogenase]','group_name'=>'Cardiac_Enzymes','price'=>'1000','description'=>''],
            ['id'=>'41','name'=>'CK-MB','group_name'=>'Cardiac_Enzymes','price'=>'1000','description'=>''],
            ['id'=>'42','name'=>'Urea','group_name'=>'Urea_and_Electrolytes','price'=>'1000','description'=>''],
            ['id'=>'43','name'=>'Sodium','group_name'=>'Urea_and_Electrolytes','price'=>'1000','description'=>''],
            ['id'=>'44','name'=>'Potassium','group_name'=>'Urea_and_Electrolytes','price'=>'1000','description'=>''],
            ['id'=>'45','name'=>'Chloride','group_name'=>'Urea_and_Electrolytes','price'=>'1000','description'=>''],
            ['id'=>'46','name'=>'Bicarbonate','group_name'=>'Urea_and_Electrolytes','price'=>'1000','description'=>''],
            ['id'=>'47','name'=>'Creatinine','group_name'=>'Urea_and_Electrolytes','price'=>'1000','description'=>''],
            ['id'=>'48','name'=>'Uric Acid','group_name'=>'Urea_and_Electrolytes','price'=>'1000','description'=>''],
            ['id'=>'49','name'=>'Total Protein','group_name'=>'Total_and_Differential_Protein','price'=>'1000','description'=>''],
            ['id'=>'50','name'=>'Albumin','group_name'=>'Total_and_Differential_Protein','price'=>'1000','description'=>''],
            ['id'=>'51','name'=>'Globulin','group_name'=>'Total_and_Differential_Protein','price'=>'1000','description'=>''],
            ['id'=>'52','name'=>'Amylase','group_name'=>'Other1','price'=>'1000','description'=>''],
            ['id'=>'53','name'=>'LDH','group_name'=>'Other1','price'=>'1000','description'=>''],
            ['id'=>'54','name'=>'Calcium','group_name'=>'Other1','price'=>'1000','description'=>''],
            ['id'=>'55','name'=>'CK','group_name'=>'Other1','price'=>'1000','description'=>''],
            ['id'=>'56','name'=>'Phosphorus','group_name'=>'Other1','price'=>'1000','description'=>''],
            ['id'=>'57','name'=>'CPR(Qualitative)','group_name'=>'Other1','price'=>'1000','description'=>''],
            ['id'=>'58','name'=>'CRP(Quantitative)','group_name'=>'Other1','price'=>'1000','description'=>''],
            ['id'=>'59','name'=>'Glucose[F,R,@hrPP]','group_name'=>'Diabetes_Tests','price'=>'1000','description'=>''],
            ['id'=>'60','name'=>'Oral Glucose Toierance Test [OGTT]','group_name'=>'Diabetes_Tests','price'=>'1000','description'=>''],
            ['id'=>'61','name'=>'HbA1C','group_name'=>'Diabetes_Tests','price'=>'1000','description'=>''],
            ['id'=>'62','name'=>'AFP','group_name'=>'Tumour_Makers','price'=>'1000','description'=>''],
            ['id'=>'63','name'=>'CA125','group_name'=>'Tumour_Makers','price'=>'1000','description'=>''],
            ['id'=>'64','name'=>'CA153','group_name'=>'Tumour_Makers','price'=>'1000','description'=>''],
            ['id'=>'65','name'=>'CA199','group_name'=>'Tumour_Makers','price'=>'1000','description'=>''],
            ['id'=>'66','name'=>'CEA','group_name'=>'Tumour_Makers','price'=>'1000','description'=>''],
            ['id'=>'67','name'=>'CEA','group_name'=>'Tumour_Makers','price'=>'1000','description'=>''],
            ['id'=>'68','name'=>'PSA(Total)','group_name'=>'Tumour_Makers','price'=>'1000','description'=>''],
            ['id'=>'69','name'=>'PSA(Free)','group_name'=>'Tumour_Makers','price'=>'1000','description'=>''],
            ['id'=>'70','name'=>'T3/FreeT3','group_name'=>'Hormones','price'=>'1000','description'=>''],
            ['id'=>'71','name'=>'T4/FreeT4','group_name'=>'Hormones','price'=>'1000','description'=>''],
            ['id'=>'72','name'=>'Beta-HCG','group_name'=>'Hormones','price'=>'1000','description'=>''],
            ['id'=>'73','name'=>'Cortisol1','group_name'=>'Hormones','price'=>'1000','description'=>''],
            ['id'=>'74','name'=>'FSH','group_name'=>'Hormones','price'=>'1000','description'=>''],
            ['id'=>'75','name'=>'LH','group_name'=>'Hormones','price'=>'1000','description'=>''],
            ['id'=>'76','name'=>'Progesterone','group_name'=>'Hormones','price'=>'1000','description'=>''],
            ['id'=>'77','name'=>'Prolactin','group_name'=>'Hormones','price'=>'1000','description'=>''],
            ['id'=>'78','name'=>'Testosterone','group_name'=>'Hormones','price'=>'1000','description'=>''],
            ['id'=>'79','name'=>'Beta-HCG(Quantitative)','group_name'=>'Hormones','price'=>'1000','description'=>''],
            ['id'=>'80','name'=>'Estradiol E2','group_name'=>'Hormones','price'=>'1000','description'=>''],
            ['id'=>'81','name'=>'Cortisol2','group_name'=>'Hormones','price'=>'1000','description'=>''],
            ['id'=>'82','name'=>'Parathyroid Hormone','group_name'=>'Hormones','price'=>'1000','description'=>''],
            ['id'=>'83','name'=>'Troponin I','group_name'=>'Cardiac_Makers1','price'=>'1000','description'=>''],
            ['id'=>'84','name'=>'Troponin T','group_name'=>'Cardiac_Makers2','price'=>'1000','description'=>''],
            ['id'=>'85','name'=>'NT-ProBNP','group_name'=>'Cardiac_Makers3','price'=>'1000','description'=>''],
            ['id'=>'86','name'=>'Troponin I, CK-MB,BNP[Alere Triage]','group_name'=>'Cardiac_Makers4','price'=>'1000','description'=>''],
            ['id'=>'87','name'=>'MP [ICT] (Malaria Parasites)','group_name'=>'Others2','price'=>'1000','description'=>''],
            ['id'=>'88','name'=>'MP Film (Bld for Malaria Parasites)','group_name'=>'Others2','price'=>'1000','description'=>''],
            ['id'=>'89','name'=>'HbA1c & CRP(Q) [NycoCard]','group_name'=>'Others2','price'=>'1000','description'=>''],
            ['id'=>'90','name'=>'MF Film (MicroFilaria)','group_name'=>'Others2','price'=>'1000','description'=>''],
            ['id'=>'91','name'=>'HBsAg (Qualitative)','group_name'=>'Infactions_Diseases_and_Others','price'=>'1000','description'=>''],
            ['id'=>'92','name'=>'HBsAg (Quantitative)','group_name'=>'Infactions_Diseases_and_Others','price'=>'1000','description'=>''],
            ['id'=>'93','name'=>'Anti-HBs (Qualitative)','group_name'=>'Infactions_Diseases_and_Others','price'=>'1000','description'=>''],
            ['id'=>'94','name'=>'Anti-HBs (Quantitative)','group_name'=>'Infactions_Diseases_and_Others','price'=>'1000','description'=>''],
            ['id'=>'95','name'=>'HBeAg','group_name'=>'Infactions_Diseases_and_Others','price'=>'1000','description'=>''],
            ['id'=>'96','name'=>'HBeAb','group_name'=>'Infactions_Diseases_and_Others','price'=>'1000','description'=>''],
            ['id'=>'97','name'=>'Anti-HBc (IgG/IgM/Total)','group_name'=>'Infactions_Diseases_and_Others','price'=>'1000','description'=>''],
            ['id'=>'98','name'=>'HBV Panel','group_name'=>'Infactions_Diseases_and_Others','price'=>'1000','description'=>''],
            ['id'=>'99','name'=>'HIV 1&2 Ab Screening','group_name'=>'Infactions_Diseases_and_Others','price'=>'1000','description'=>''],
            ['id'=>'100','name'=>'HIV 1&2 Ab ELISA','group_name'=>'Infactions_Diseases_and_Others','price'=>'1000','description'=>''],
            ['id'=>'101','name'=>'HIV 1&2 Confirmation','group_name'=>'Infactions_Diseases_and_Others','price'=>'1000','description'=>''],
            ['id'=>'102','name'=>'P24 HIV Ag','group_name'=>'Infactions_Diseases_and_Others','price'=>'1000','description'=>''],
            ['id'=>'103','name'=>'HCVAb','group_name'=>'Infactions_Diseases_and_Others','price'=>'1000','description'=>''],
            ['id'=>'104','name'=>'HAV Ab (IgG/IgM)','group_name'=>'Infactions_Diseases_and_Others','price'=>'1000','description'=>''],
            ['id'=>'105','name'=>'VDRL [Syphilis]','group_name'=>'Infactions_Diseases_and_Others','price'=>'1000','description'=>''],
            ['id'=>'106','name'=>'TPHA','group_name'=>'Infactions_Diseases_and_Others','price'=>'1000','description'=>''],
            ['id'=>'107','name'=>'Widal Test','group_name'=>'Infactions_Diseases_and_Others','price'=>'1000','description'=>''],
            ['id'=>'108','name'=>'MF IgG/IgM (ICT) [Microfilaris]','group_name'=>'Infactions_Diseases_and_Others','price'=>'1000','description'=>''],
            ['id'=>'109','name'=>'Chikungunya Ab(IgM)','group_name'=>'Infactions_Diseases_and_Others','price'=>'1000','description'=>''],
            ['id'=>'110','name'=>'Salmonella IgG/IgM','group_name'=>'Infactions_Diseases_and_Others','price'=>'1000','description'=>''],
            ['id'=>'111','name'=>'Rubella IgG/IgM','group_name'=>'Infactions_Diseases_and_Others','price'=>'1000','description'=>''],
            ['id'=>'112','name'=>'Leptospiral Ab (IgG/IgM)','group_name'=>'Infactions_Diseases_and_Others','price'=>'1000','description'=>''],
            ['id'=>'113','name'=>'H.pylori (IgG/IgM)','group_name'=>'Infactions_Diseases_and_Others','price'=>'1000','description'=>''],
            ['id'=>'114','name'=>'Dengue NS1Ag+IgM/IgG','group_name'=>'Infactions_Diseases_and_Others','price'=>'1000','description'=>''],
            ['id'=>'115','name'=>'Dengue Ab IgG/IgM','group_name'=>'Infactions_Diseases_and_Others','price'=>'1000','description'=>''],
            ['id'=>'116','name'=>'ICT TB (IgG/IgM)','group_name'=>'Infactions_Diseases_and_Others','price'=>'1000','description'=>''],
            ['id'=>'117','name'=>'Tsutsugamushi IgG/IgM(Scrub Typhus)','group_name'=>'Infactions_Diseases_and_Others','price'=>'1000','description'=>''],
            ['id'=>'118','name'=>'RA','group_name'=>'Infactions_Diseases_and_Others','price'=>'1000','description'=>''],
            ['id'=>'119','name'=>'ASO (Qualitative/Quantitative)','group_name'=>'Infactions_Diseases_and_Others','price'=>'1000','description'=>''],
            ['id'=>'120','name'=>'ANF/ANA/Anti ds DNA','group_name'=>'Infactions_Diseases_and_Others','price'=>'1000','description'=>''],
            ['id'=>'121','name'=>'Ab for Aspergillus fumigatus','group_name'=>'Fungal_Serology','price'=>'1000','description'=>''],
            ['id'=>'122','name'=>'Ab for Aspergillus flavus','group_name'=>'Fungal_Serology','price'=>'1000','description'=>''],
            ['id'=>'123','name'=>'Ab for Aspergillus niger','group_name'=>'Fungal_Serology','price'=>'1000','description'=>''],
            ['id'=>'124','name'=>'Ab for Histoplasma capsulatum','group_name'=>'Fungal_Serology','price'=>'1000','description'=>''],
            ['id'=>'125','name'=>'Ab for Candida albicans','group_name'=>'Fungal_Serology','price'=>'1000','description'=>''],
            ['id'=>'126','name'=>'Ab for Blastomyces dermatitidis','group_name'=>'Fungal_Serology','price'=>'1000','description'=>''],
            ['id'=>'127','name'=>'Ab for Coccidioides immitis','group_name'=>'Fungal_Serology','price'=>'1000','description'=>''],
            ['id'=>'128','name'=>'Cryptococcus neoformans Ag (Serum) (CSF)','group_name'=>'Fungal_Serology','price'=>'1000','description'=>''],
            ['id'=>'129','name'=>'Blood','group_name'=>'Microbiology','price'=>'1000','description'=>''],
            ['id'=>'130','name'=>'Urine','group_name'=>'Microbiology','price'=>'1000','description'=>''],
            ['id'=>'131','name'=>'Aspirated Fluid','group_name'=>'Microbiology','price'=>'1000','description'=>''],
            ['id'=>'132','name'=>'Body Fluid','group_name'=>'Microbiology','price'=>'1000','description'=>''],
            ['id'=>'133','name'=>'Sputum','group_name'=>'Microbiology','price'=>'1000','description'=>''],
            ['id'=>'134','name'=>'Stool','group_name'=>'Microbiology','price'=>'1000','description'=>''],
            ['id'=>'135','name'=>'Pus','group_name'=>'Microbiology','price'=>'1000','description'=>''],
            ['id'=>'136','name'=>'Throat Swab','group_name'=>'Microbiology','price'=>'1000','description'=>''],
            ['id'=>'137','name'=>'Wound Swab','group_name'=>'Microbiology','price'=>'1000','description'=>''],
            ['id'=>'138','name'=>'Ear Swab','group_name'=>'Microbiology','price'=>'1000','description'=>''],
            ['id'=>'139','name'=>'High Vaginal Swab(HVS)','group_name'=>'Microbiology','price'=>'1000','description'=>''],
            ['id'=>'140','name'=>'Fungal Direct Microscopy & Culture','group_name'=>'Microbiology','price'=>'1000','description'=>''],
            ['id'=>'141','name'=>'AfB Culture','group_name'=>'Microbiology','price'=>'1000','description'=>''],
            ['id'=>'142','name'=>'Urine Routine Examination [RE]','group_name'=>'Urine','price'=>'1000','description'=>''],
            ['id'=>'143','name'=>'Urine for ketone bodies','group_name'=>'Urine','price'=>'1000','description'=>''],
            ['id'=>'144','name'=>'Urine for Albumin','group_name'=>'Urine','price'=>'1000','description'=>''],
            ['id'=>'145','name'=>'Urine for Suger','group_name'=>'Urine','price'=>'1000','description'=>''],
            ['id'=>'146','name'=>'Urine Pregnancy Test(HCG/UCG)','group_name'=>'Urine','price'=>'1000','description'=>''],
            ['id'=>'147','name'=>'Urine Bence Jones Protein','group_name'=>'Urine','price'=>'1000','description'=>''],
            ['id'=>'148','name'=>'Stool Routine Examinnation [RE]','group_name'=>'Stool','price'=>'1000','description'=>''],
            ['id'=>'149','name'=>'Stool for Reducing Substance','group_name'=>'Stool','price'=>'1000','description'=>''],
            ['id'=>'150','name'=>'Stool for AFB','group_name'=>'Stool','price'=>'1000','description'=>''],
            ['id'=>'151','name'=>'Stool for occult blood','group_name'=>'Stool','price'=>'1000','description'=>''],
            ['id'=>'152','name'=>'H.pylori (Stool)','group_name'=>'Stool','price'=>'1000','description'=>''],
            ['id'=>'153','name'=>'Hanging-drop Preparation','group_name'=>'Stool','price'=>'1000','description'=>''],
            ['id'=>'154','name'=>'Stool for Rota virus','group_name'=>'Stool','price'=>'1000','description'=>''],
            ['id'=>'155','name'=>'Stool for Cholera Ag','group_name'=>'Stool','price'=>'1000','description'=>''],
            ['id'=>'156','name'=>'Fluid Routine Examination[RE](CSF/Pleural/Ascitic)','group_name'=>'Others3','price'=>'1000','description'=>''],
            ['id'=>'157','name'=>'Sputum for AFB (Concentrated Method)','group_name'=>'Others3','price'=>'1000','description'=>''],
            ['id'=>'158','name'=>'Semen Analysis','group_name'=>'Others3','price'=>'1000','description'=>''],
            ['id'=>'159','name'=>'Tuberculin Test','group_name'=>'Others3','price'=>'1000','description'=>''],
            ['id'=>'160','name'=>'Chlamydia Ag Test (Endocervical/Urethral Swab)','group_name'=>'Others3','price'=>'1000','description'=>''],
            ['id'=>'161','name'=>'Urine Electrolytes','group_name'=>'Chemical_Pathology','price'=>'1000','description'=>''],
            ['id'=>'162','name'=>'Urine Sodium','group_name'=>'Chemical_Pathology','price'=>'1000','description'=>''],
            ['id'=>'163','name'=>'Urine Chloride','group_name'=>'Chemical_Pathology','price'=>'1000','description'=>''],
            ['id'=>'164','name'=>'Urine Creatinine','group_name'=>'Chemical_Pathology','price'=>'1000','description'=>''],
            ['id'=>'165','name'=>'Urine Protein Creatinine Ratio','group_name'=>'Chemical_Pathology','price'=>'1000','description'=>''],
            ['id'=>'166','name'=>'24 hours urine protein','group_name'=>'Chemical_Pathology','price'=>'1000','description'=>''],
            ['id'=>'167','name'=>'24 hours urine calcium','group_name'=>'Chemical_Pathology','price'=>'1000','description'=>''],
            ['id'=>'168','name'=>'24 hours urine uric acid','group_name'=>'Chemical_Pathology','price'=>'1000','description'=>''],
            ['id'=>'169','name'=>'Urine for Microalbumin','group_name'=>'Chemical_Pathology','price'=>'1000','description'=>''],
            ['id'=>'170','name'=>'Biopsy','group_name'=>'Histopathology','price'=>'1000','description'=>''],
            ['id'=>'171','name'=>'Cytology','group_name'=>'Histopathology','price'=>'1000','description'=>''],
            ['id'=>'172','name'=>'PapSmear','group_name'=>'Histopathology','price'=>'1000','description'=>''],
            ['id'=>'173','name'=>'FNAC','group_name'=>'Histopathology','price'=>'1000','description'=>''],
            ['id'=>'174','name'=>'G6PD','group_name'=>'Neonatal_Screening_Tests','price'=>'1000','description'=>''],
            ['id'=>'175','name'=>'TSH','group_name'=>'Neonatal_Screening_Tests','price'=>'1000','description'=>''],
            ['id'=>'176','name'=>'Phenylketonuria [PKU]','group_name'=>'Neonatal_Screening_Tests','price'=>'1000','description'=>'']
        );

        DB::table('investigations')->insert($tempArrays);
    }
}