<?php
/**
 * Created by PhpStorm.
 * Author: Wai Yan Aung
 * Date: 11/8/2016
 * Time: 11:22 AM
 */

use Illuminate\Database\Seeder;
class Default_InvestigationPriceTrackingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('setup_price_tracking')->where('table_name', '=', 'investigations')->delete();

        $objs = array(
            ['table_name'=>'investigations', 'table_id'=>'1', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'2', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'3', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'4', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'5', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'6', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'7', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'8', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'9', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'10', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'11', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'12', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'13', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'14', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'15', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'16', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'17', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'18', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'19', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'20', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'21', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'22', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'23', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'24', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'25', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'26', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'27', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'28', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'29', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'30', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'31', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'32', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'33', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'34', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'35', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'36', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'37', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'38', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'39', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'40', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'41', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'42', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'43', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'44', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'45', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'46', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'47', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'48', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'49', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'50', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'51', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'52', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'53', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'54', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'55', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'56', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'57', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'58', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'59', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'60', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'61', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'62', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'63', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'64', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'65', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'66', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'67', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'68', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'69', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'70', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'71', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'72', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'73', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'74', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'75', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'76', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'77', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'78', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'79', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'80', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'81', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'82', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'83', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'84', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'85', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'86', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'87', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'88', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'89', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'90', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'91', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'92', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'93', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'94', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'95', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'96', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'97', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'98', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'99', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'100', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'101', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'102', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'103', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'104', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'105', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'106', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'107', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'108', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'109', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'110', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'111', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'112', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'113', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'114', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'115', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'116', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'117', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'118', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'119', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'120', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'121', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'122', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'123', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'124', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'125', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'126', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'127', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'128', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'129', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'130', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'131', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'132', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'133', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'134', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'135', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'136', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'137', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'138', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'139', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'140', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'141', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'142', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'143', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'144', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'145', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'146', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'147', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'148', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'149', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'150', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'151', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'152', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'153', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'154', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'155', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'156', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'157', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'158', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'159', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'160', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'161', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'162', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'163', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'164', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'165', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'166', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'167', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'168', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'169', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'170', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'171', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'172', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'173', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'174', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'175', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000'],
            ['table_name'=>'investigations', 'table_id'=>'176', 'table_id_type'=>'integer', 'action'=>'create', 'old_price' =>'0', 'new_price' =>'1000']
        );

        DB::table('setup_price_tracking')->insert($objs);
    }
}