<?php
/**
 * Created by PhpStorm.
 * Author: Wai Yan Aung
 * Date: 7/25/2016
 * Time: 11:48 AM
 */
?>

@extends('layouts.master')
@section('title','Invoice API Detail')
@section('content')

        <!-- begin #content -->
<div id="content" class="content">
    <h1 class="page-header">API List</h1>
    <div class="row">
        <ul class="nav nav-tabs">
            <li><a href="/apilist/syncdownapi" class="api-tab">Sync Down API</a></li>
            <li class="active"><a href="#" class="api-active-tab">Invoice API</a></li>
            <li><a href="/apilist/enquiryapi" class="api-tab">Enquiry API</a></li>
            <li><a href="/apilist/scheduleapi" class="api-tab">Schedule API</a></li>
            <li><a href="/apilist/patientpackageapi" class="api-tab">Patient Package API</a></li>
            <li><a href="/apilist/waytrackingapi" class="api-tab">Way Tracking API</a></li>
            <li><a href="/apilist/patientapi" class="api-tab">Patient API</a></li>
        </ul>
    </div>

    <div class="row">
        <h4>URL</h4>
        <p><b>http://localhost:8000/api/invoice/upload/v3</b></p>
    </div>
    <hr>
    <div class="row">
        <h4>Description</h4>
        <p>This API is for uploading invoice data from tablet to server.</p>
        <ol>
            <li>Tablet uploads tables with data according to invoice API input format.</li>
            <li>In server side, activation keys from input json are checked.</li>
            <li>If valid, proceeds to next step. Else,stops by returning error message.</li>
            <li>In server side, check if keys of table(table names) exist.</li>
            <li>If key exists, gets IDs from value field and clear data with that IDs from database. Then, insert data into database.</li>
            <li>If tables are in header & detail format, check isset() for header data first, clear detail data first, and insert header data first.</li>
            <li>Else, skip that table and continues to next table.</li>
            <li>Repeat this procedure for all tables.</li>
            <li>If there is an error in data insertion, database is rolled back to its original state.</li>
            <li>After all tables are successfully inserted, commit database.</li>
            <li>After commit, for return data, check if schedule exists.</li>
            <li>If schedule exists, 'enquiries,schedules,schedule_treatment_histories,patients,patient_medical_history,patient_family_history,patient_surgery_history,patient_family_member' are retrieved from database according to patient_id in schedules and returned to tablet.</li>
            <li>If schedule does not exist, only enquiries within last three days and status='new' are retrieved and returned to tablet. Other fields are returned with empty array.</li>
            <li>API logs are recorded.</li>
        </ol>
    </div>
    <hr>
    <div class="row">
        <h4>Input Format</h4>
        <ul style="list-style-type:circle">
            <li>
                invoices
                <ul style="list-style-type:none">
                    <li>invoice_detail</li>
                </ul>
            </li>
            <li>
                enquiries
                <ul style="list-style-type:none">
                    <li>enquiry_detail</li>
                </ul>
            </li>
            <li>
                schedules
                <ul style="list-style-type:none">
                    <li>schedule_detail</li>
                </ul>
            </li>
            <li>schedule_trackings</li>
            <li>schedule_patient_vitals</li>
            <li>schedule_patient_chief_complaint</li>
            <li>patient_medical_history</li>
            <li>medical_history ( if new create )</li>
            <li>patient_surgsery_history</li>
            <li>patient_family_history</li>
            <li>family_histories(if new create)</li>
            <li>patient_family_member(if new create)</li>
            <li>schedule_treatment_history</li>
            <li>product (if new create)</li>
            <li>route (if new create)</li>
            <li>schedule_physical_general_pupils_head</li>
            <li>schedule_physical_heart_lungs</li>
            <li>schedule_physical_abdomen_extre_neuro</li>
            <li>schedule_provisional_diagnosis</li>
            <li>schedule_investigation</li>
            <li>schedule_physiotherapy_neuro</li>
            <li>patient_physiotherapy_neuro_general</li>
            <li>patient_physiotherapy_neuro_limb</li>
            <li>patient_physiotherapy_neuro_functional_performance1</li>
            <li>patient_physiotherapy_neuro_functional_performance2</li>
            <li>patient_physiotherapy_neuro_functional_performance3</li>
            <li>schedule_physiotherapy_musculo</li>
            <li>patient_physiotherapy_musculo_1_and_2</li>
            <li>patient_physiotherapy_musculo_3_sitting</li>
            <li>patient_physiotherapy_musculo_3_standing</li>
            <li>patient_physiotherapy_musculo_4_1and2</li>
            <li>patient_physiotherapy_musculo_4_3</li>
            <li>patient_physiotherapy_musculo_4_4and5</li>
            <li>schedule_trackings</li>
            <li>nutrition</li>
        </ul>
    </div>
    <hr>
    <div class="row">
        <h4>Sample Input JSON</h4>
        <pre>
            {
            "site_activation_key": "1234567",
            "tablet_activation_key": "aaa",
            "user_id": "U0001",
            "data": [
            {
            "invoices": [
            {
            "accepted_by": "2",
            "id": "U0011",
            "patient_id": "U0006",
            "package_id": "3",
            "package_price": "3000",
            "patient_package_id": "1",
            "schedule_end_time": "10:34:34",
            "schedule_start_time": "2:23:32",
            "schedule_id": "u0032",
            "status": "2",
            "tax_rate": "39",
            "total_car_amount": "0",
            "total_consultant_discount_amount": "0",
            "total_consultant_fee": "0",
            "total_disc_amt": "0",
            "total_disc_percent": "30",
            "total_investigation_amount": "20000",
            "total_medication_amount": "34334",
            "total_nett_amt_w_disc": "0",
            "total_nett_amt_wo_disc": "30",
            "total_other_service_amount": "2399",
            "total_payable_amt": "20000",
            "total_service_amount": "0",
            "total_tax_amt": "303",
            "township_id": "1",
            "zone_id": "1",
            "type": "test",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": "",
            "created_at": "2016-10-05 13:25:03",
            "updated_at": "2016-10-05 13:25:03",
            "deleted_at": "",
            "invoice_detail": [
            {
            "type": "1",
            "product_id": "1",
            "other_service_remark": "0",
            "other_service": "other Service0",
            "consultant_discount_percentage": "0",
            "consultant_fee": "0",
            "invoice_id": "U0011",
            "consultant_id": 0,
            "consultant_discount_amount": 0.0,
            "other_service_price": 0.0,
            "service_price": 0.0,
            "product_amount": 0.0,
            "car_type_price": 0.0,
            "product_price": 0.0,
            "product_qty": 0,
            "car_type_setup_id": 1,
            "service_type_id": 1,
            "car_type": 0
            },
            {
            "type": "1",
            "product_id": "1",
            "other_service_remark": "1",
            "other_service": "other Service1",
            "consultant_discount_percentage": "1",
            "consultant_fee": "1",
            "invoice_id": "U0011",
            "consultant_id": 1,
            "consultant_discount_amount": 1.0,
            "other_service_price": 1.0,
            "service_price": 1.0,
            "product_amount": 1.0,
            "car_type_price": 1.0,
            "product_price": 1.0,
            "product_qty": 1,
            "car_type_setup_id": 1,
            "service_type_id": 1,
            "car_type": 1
            }
            ]
            },
            {
            "accepted_by": "3",
            "id": "U0012",
            "patient_id": "U0007",
            "package_id": "3",
            "package_price": "3000",
            "patient_package_id": "1",
            "schedule_end_time": "10:34:34",
            "schedule_start_time": "2:23:32",
            "schedule_id": "u0032",
            "status": "2",
            "tax_rate": "39",
            "total_car_amount": "1",
            "total_consultant_discount_amount": "1",
            "total_consultant_fee": "1",
            "total_disc_amt": "1",
            "total_disc_percent": "30",
            "total_investigation_amount": "20000",
            "total_medication_amount": "34334",
            "total_nett_amt_w_disc": "1",
            "total_nett_amt_wo_disc": "30",
            "total_other_service_amount": "2399",
            "total_payable_amt": "20000",
            "total_service_amount": "1",
            "total_tax_amt": "303",
            "township_id": "1",
            "zone_id": "1",
            "type": "test",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": "",
            "created_at": "2016-10-04 13:25:03",
            "updated_at": "2016-10-04 13:25:03",
            "deleted_at": "",
            "invoice_detail": [
            {
            "type": "1",
            "product_id": "1",
            "other_service_remark": "0",
            "other_service": "other Service0",
            "consultant_discount_percentage": "0",
            "consultant_fee": "0",
            "invoice_id": "U0012",
            "consultant_id": 0,
            "consultant_discount_amount": 0.0,
            "other_service_price": 0.0,
            "service_price": 0.0,
            "product_amount": 0.0,
            "car_type_price": 0.0,
            "product_price": 0.0,
            "product_qty": 0,
            "car_type_setup_id": 1,
            "service_type_id": 1,
            "car_type": 0
            },
            {
            "type": "1",
            "product_id": "1",
            "other_service_remark": "1",
            "other_service": "other Service1",
            "consultant_discount_percentage": "1",
            "consultant_fee": "1",
            "invoice_id": "U0012",
            "consultant_id": 1,
            "consultant_discount_amount": 1.0,
            "other_service_price": 1.0,
            "service_price": 1.0,
            "product_amount": 1.0,
            "car_type_price": 1.0,
            "product_price": 1.0,
            "product_qty": 1,
            "car_type_setup_id": 1,
            "service_type_id": 1,
            "car_type": 1
            }
            ]
            }
            ],
            "medical_history": [
            {
            "id": "U0001",
            "name": "test1",
            "description": "test1 test1 test1 test1",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": "",
            "created_at": "2016-10-04 13:25:03",
            "updated_at": "2016-10-04 13:25:03",
            "deleted_at": ""
            },
            {
            "id": "U0002",
            "name": "test2",
            "description": "test2 test2 test2 test2",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": "",
            "created_at": "2016-10-04 13:25:03",
            "updated_at": "2016-10-04 13:25:03",
            "deleted_at": ""
            }
            ],
            "family_histories": [
            {
            "id": "U0001",
            "name": "test1",
            "description": "test1 test1 test1 test1",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": "",
            "created_at": "2016-10-04 13:25:03",
            "updated_at": "2016-10-04 13:25:03",
            "deleted_at": ""
            },
            {
            "id": "U0002",
            "name": "test2",
            "description": "test2 test2 test2 test2",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": "",
            "created_at": "2016-10-04 13:25:03",
            "updated_at": "2016-10-04 13:25:03",
            "deleted_at": ""
            }
            ],
            "patient_family_history": [
            {
            "id": "U0001",
            "patient_id": "U0004",
            "family_history_id": "1",
            "family_member_id": "U0001",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": "",
            "created_at": "2016-10-04 13:25:03",
            "updated_at": "2016-10-04 13:25:03",
            "deleted_at": ""
            },
            {
            "id": "U0002",
            "patient_id": "U0005",
            "family_history_id": "2",
            "family_member_id": "U0001",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": "",
            "created_at": "2016-10-04 13:25:03",
            "updated_at": "2016-10-04 13:25:03",
            "deleted_at": ""
            }
            ],
            "patient_family_member": [
            {
            "id": "U001000000001",
            "name": "test1",
            "description": "Aunt",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "2016-10-04 13:25:03",
            "updated_at": "2016-10-04 13:25:03",
            "deleted_at": ""
            },
            {
            "id": "U001000000002",
            "name": "test2",
            "description": "Aunt",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "2016-10-04 13:25:03",
            "updated_at": "2016-10-04 13:25:03",
            "deleted_at": ""
            }
            ],
            "patient_medical_history": [
            {
            "id": "U0001",
            "patient_id": "U0002",
            "medical_history_id": "U0001",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": "",
            "created_at": "2016-10-04 13:25:03",
            "updated_at": "2016-10-04 13:25:03",
            "deleted_at": ""
            },
            {
            "id": "U0002",
            "patient_id": "U0002",
            "medical_history_id": "U0002",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": "",
            "created_at": "2016-10-04 13:25:03",
            "updated_at": "2016-10-04 13:25:03",
            "deleted_at": ""
            }
            ],
            "patient_surgery_history": [
            {
            "id": "U00100000001",
            "patient_id": "U0002",
            "description": "test1 test1 test1",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": "",
            "created_at": "2016-10-04 13:25:03",
            "updated_at": "2016-10-04 13:25:03",
            "deleted_at": ""
            },
            {
            "id": "U00100000002",
            "patient_id": "U0002",
            "description": "test2 test2 test2",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": "",
            "created_at": "2016-10-04 13:25:03",
            "updated_at": "2016-10-04 13:25:03",
            "deleted_at": ""
            }
            ],
            "patient_physiothreapy_musculo_1_and_2": [
            {
            "cheif_comlaint_sensation_others": "test test test ",
            "chief_complaint_aggravating_factors": "test test test",
            "chief_complaint_alternating_factors": "test test test",
            "chief_complaint_constant": "0",
            "chief_complaint_dull_ache": "1",
            "chief_complaint_duration": "0",
            "chief_complaint_giving_way": "1",
            "chief_complaint_intermittent": "0",
            "chief_complaint_locking": "0",
            "chief_complaint_night_pain": "0",
            "chief_complaint_numbness": "0",
            "chief_complaint_onset": "0",
            "chief_complaint_others": "1",
            "chief_complaint_pain_grade": "1",
            "chief_complaint_pin_and_needles": "1",
            "chief_complaint_popping": "0",
            "chief_complaint_sharp": "1",
            "chief_complaint_site_and_spread_of_pain": "1",
            "chief_complaint_thorbbing": "0",
            "chief_complaint_tingling": "0",
            "created_at": "",
            "created_by": "U0001",
            "deleted_at": "",
            "deleted_by": "",
            "diagnosis": "test diagnosis",
            "observation_deformity": "test test",
            "observation_gait": "test",
            "observation_heat": "0",
            "observation_loss_of_function": "1",
            "observation_muscule_spasm": "0",
            "observation_posture": "1",
            "observation_swelling": "0",
            "observation_tendemess": "1",
            "patients_id": "U0004",
            "previous_medical_history": "history test",
            "referred_by": "Dr. Mya Mya",
            "updated_at": "",
            "updated_by": ""
            },
            {
            "cheif_comlaint_sensation_others": "test test test ",
            "chief_complaint_aggravating_factors": "test test test",
            "chief_complaint_alternating_factors": "test test test",
            "chief_complaint_constant": "0",
            "chief_complaint_dull_ache": "1",
            "chief_complaint_duration": "0",
            "chief_complaint_giving_way": "1",
            "chief_complaint_intermittent": "0",
            "chief_complaint_locking": "0",
            "chief_complaint_night_pain": "0",
            "chief_complaint_numbness": "0",
            "chief_complaint_onset": "0",
            "chief_complaint_others": "1",
            "chief_complaint_pain_grade": "1",
            "chief_complaint_pin_and_needles": "1",
            "chief_complaint_popping": "0",
            "chief_complaint_sharp": "1",
            "chief_complaint_site_and_spread_of_pain": "1",
            "chief_complaint_thorbbing": "0",
            "chief_complaint_tingling": "0",
            "created_at": "",
            "created_by": "U0001",
            "deleted_at": "",
            "deleted_by": "",
            "diagnosis": "test diagnosis",
            "observation_deformity": "test test",
            "observation_gait": "test",
            "observation_heat": "0",
            "observation_loss_of_function": "1",
            "observation_muscule_spasm": "0",
            "observation_posture": "1",
            "observation_swelling": "0",
            "observation_tendemess": "1",
            "patients_id": "U0005",
            "previous_medical_history": "history test",
            "referred_by": "Dr. Mya Mya",
            "updated_at": "",
            "updated_by": ""
            }
            ],
            "patient_physiotherapy_musculo_3_sitting": [
            {
            "patient_id": "U0004",
            "joint": "joint",
            "flexion_normal": "0",
            "flexion_minimum": "0",
            "flexion_moderate": "0",
            "flexion_maximum": "1",
            "extension_normal": "1",
            "extension_minimum": "0",
            "extension_moderate": "0",
            "extension_maximum": "0",
            "abduction_normal": "0",
            "abduction_minimum": "1",
            "abduction_moderate": "0",
            "abduction_maximum": "0",
            "adduction_normal": "0",
            "adduction_minimum": "0",
            "adduction_moderate": "1",
            "adduction_maximum": "0",
            "medical_rotation_normal": "0",
            "medical_rotation_minimum": "0",
            "medical_rotation_moderate": "0",
            "medical_rotation_maximum": "1",
            "lateral_rotation_normal": "1",
            "lateral_rotation_minimum": "0",
            "lateral_rotation_moderate": "0",
            "lateral_rotation_maximum": "0",
            "side_flexion_normal": "1",
            "side_flexion_minimum": "0",
            "side_flexion_moderate": "0",
            "side_flexion_maximum": "0",
            "rotation_to_right_normal": "0",
            "rotation_to_right_minimum": "0",
            "rotation_to_right_moderate": "0",
            "rotation_to_right_maximum": "1",
            "rotation_to_left_normal": "0",
            "rotation_to_left_minimum": "1",
            "rotation_to_left_moderate": "0",
            "rotation_to_left_maximum": "0",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            },
            {
            "patient_id": "U0005",
            "joint": "joint",
            "flexion_normal": "0",
            "flexion_minimum": "0",
            "flexion_moderate": "0",
            "flexion_maximum": "1",
            "extension_normal": "1",
            "extension_minimum": "0",
            "extension_moderate": "0",
            "extension_maximum": "0",
            "abduction_normal": "0",
            "abduction_minimum": "1",
            "abduction_moderate": "0",
            "abduction_maximum": "0",
            "adduction_normal": "0",
            "adduction_minimum": "0",
            "adduction_moderate": "1",
            "adduction_maximum": "0",
            "medical_rotation_normal": "0",
            "medical_rotation_minimum": "0",
            "medical_rotation_moderate": "0",
            "medical_rotation_maximum": "1",
            "lateral_rotation_normal": "1",
            "lateral_rotation_minimum": "0",
            "lateral_rotation_moderate": "0",
            "lateral_rotation_maximum": "0",
            "side_flexion_normal": "1",
            "side_flexion_minimum": "0",
            "side_flexion_moderate": "0",
            "side_flexion_maximum": "0",
            "rotation_to_right_normal": "0",
            "rotation_to_right_minimum": "0",
            "rotation_to_right_moderate": "0",
            "rotation_to_right_maximum": "1",
            "rotation_to_left_normal": "0",
            "rotation_to_left_minimum": "1",
            "rotation_to_left_moderate": "0",
            "rotation_to_left_maximum": "0",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            }
            ],
            "patient_physiotherapy_musculo_3_standing": [
            {
            "patient_id": "U0004",
            "joint": "joint",
            "flexion_normal": "0",
            "flexion_minimum": "0",
            "flexion_moderate": "0",
            "flexion_maximum": "1",
            "extension_normal": "1",
            "extension_minimum": "0",
            "extension_moderate": "0",
            "extension_maximum": "0",
            "abduction_normal": "0",
            "abduction_minimum": "1",
            "abduction_moderate": "0",
            "abduction_maximum": "0",
            "adduction_normal": "0",
            "adduction_minimum": "0",
            "adduction_moderate": "1",
            "adduction_maximum": "0",
            "medical_rotation_normal": "0",
            "medical_rotation_minimum": "0",
            "medical_rotation_moderate": "0",
            "medical_rotation_maximum": "1",
            "lateral_rotation_normal": "1",
            "lateral_rotation_minimum": "0",
            "lateral_rotation_moderate": "0",
            "lateral_rotation_maximum": "0",
            "side_flexion_normal": "1",
            "side_flexion_minimum": "0",
            "side_flexion_moderate": "0",
            "side_flexion_maximum": "0",
            "rotation_to_right_normal": "0",
            "rotation_to_right_minimum": "0",
            "rotation_to_right_moderate": "0",
            "rotation_to_right_maximum": "1",
            "rotation_to_left_normal": "0",
            "rotation_to_left_minimum": "1",
            "rotation_to_left_moderate": "0",
            "rotation_to_left_maximum": "0",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            },
            {
            "patient_id": "U0005",
            "joint": "joint",
            "flexion_normal": "0",
            "flexion_minimum": "0",
            "flexion_moderate": "0",
            "flexion_maximum": "1",
            "extension_normal": "1",
            "extension_minimum": "0",
            "extension_moderate": "0",
            "extension_maximum": "0",
            "abduction_normal": "0",
            "abduction_minimum": "1",
            "abduction_moderate": "0",
            "abduction_maximum": "0",
            "adduction_normal": "0",
            "adduction_minimum": "0",
            "adduction_moderate": "1",
            "adduction_maximum": "0",
            "medical_rotation_normal": "0",
            "medical_rotation_minimum": "0",
            "medical_rotation_moderate": "0",
            "medical_rotation_maximum": "1",
            "lateral_rotation_normal": "1",
            "lateral_rotation_minimum": "0",
            "lateral_rotation_moderate": "0",
            "lateral_rotation_maximum": "0",
            "side_flexion_normal": "1",
            "side_flexion_minimum": "0",
            "side_flexion_moderate": "0",
            "side_flexion_maximum": "0",
            "rotation_to_right_normal": "0",
            "rotation_to_right_minimum": "0",
            "rotation_to_right_moderate": "0",
            "rotation_to_right_maximum": "1",
            "rotation_to_left_normal": "0",
            "rotation_to_left_minimum": "1",
            "rotation_to_left_moderate": "0",
            "rotation_to_left_maximum": "0",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            }
            ],
            "patient_physiotherapy_musculo_4_1and2": [
            {
            "patient_id": "U0004",
            "slr_plus": "0",
            "slr_minus": "1",
            "ehl_plus": "0",
            "ehl_minus": "1",
            "femoral_nerve_plus": "0",
            "femoral_nerve_minus": "1",
            "empty_can_test_plus": "0",
            "empty_can_test_minus": "1",
            "neer_test_plus": "1",
            "neer_test_minus": "0",
            "hawkin_test_plus": "1",
            "hawkin_test_minus": "0",
            "gerber_life_off_test_plus": "0",
            "gerber_life_off_test_minus": "1",
            "drop_arm_test_plus": "1",
            "drop_arm_test_minus": "0",
            "crank_test_plus": "1",
            "crank_test_minus": "0",
            "apprehension_test_plus": "1",
            "apprehension_test_minus": "0",
            "yergason_test_plus": "1",
            "yergason_test_minus": "0",
            "anterior_drawer_test_plus": "1",
            "anterior_drawer_test_minus": "0",
            "posterior_drawer_test_plus": "1",
            "posterior_drawer_test_minus": "0",
            "varus_stress_test_plus": "1",
            "varus_stress_test_minus": "0",
            "valgus_stress_test_plus": "1",
            "valgus_stress_test_minus": "0",
            "mc_murray_test_plus": "1",
            "mc_murray_test_minus": "0",
            "flexion": "test",
            "extension": "test",
            "abduction": "test",
            "adduction": "test",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            },
            {
            "patient_id": "U0005",
            "slr_plus": "0",
            "slr_minus": "1",
            "ehl_plus": "0",
            "ehl_minus": "1",
            "femoral_nerve_plus": "0",
            "femoral_nerve_minus": "1",
            "empty_can_test_plus": "0",
            "empty_can_test_minus": "1",
            "neer_test_plus": "1",
            "neer_test_minus": "0",
            "hawkin_test_plus": "1",
            "hawkin_test_minus": "0",
            "gerber_life_off_test_plus": "0",
            "gerber_life_off_test_minus": "1",
            "drop_arm_test_plus": "1",
            "drop_arm_test_minus": "0",
            "crank_test_plus": "1",
            "crank_test_minus": "0",
            "apprehension_test_plus": "1",
            "apprehension_test_minus": "0",
            "yergason_test_plus": "1",
            "yergason_test_minus": "0",
            "anterior_drawer_test_plus": "1",
            "anterior_drawer_test_minus": "0",
            "posterior_drawer_test_plus": "1",
            "posterior_drawer_test_minus": "0",
            "varus_stress_test_plus": "1",
            "varus_stress_test_minus": "0",
            "valgus_stress_test_plus": "1",
            "valgus_stress_test_minus": "0",
            "mc_murray_test_plus": "1",
            "mc_murray_test_minus": "0",
            "flexion": "test",
            "extension": "test",
            "abduction": "test",
            "adduction": "test",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            }
            ],
            "patient_physiotherapy_musculo_4_3": [
            {
            "patient_id": "U0004",
            "ms_acting_on_joint": "test",
            "flexors_0": "0",
            "flexors_1": "1",
            "flexors_2": "0",
            "flexors_3": "0",
            "flexors_4": "0",
            "flexors_5": "0",
            "extensors_0": "1",
            "extensors_1": "0",
            "extensors_2": "0",
            "extensors_3": "0",
            "extensors_4": "0",
            "extensors_5": "0",
            "abductors_0": "1",
            "abductors_1": "0",
            "abductors_2": "0",
            "abductors_3": "0",
            "abductors_4": "0",
            "abductors_5": "0",
            "adductors_0": "1",
            "adductors_1": "0",
            "adductors_2": "0",
            "adductors_3": "0",
            "adductors_4": "0",
            "adductors_5": "0",
            "medial_rotators_0": "0",
            "medial_rotators_1": "1",
            "medial_rotators_2": "0",
            "medial_rotators_3": "0",
            "medial_rotators_4": "0",
            "medial_rotators_5": "0",
            "lateral_rotators_0": "0",
            "lateral_rotators_1": "0",
            "lateral_rotators_2": "1",
            "lateral_rotators_3": "0",
            "lateral_rotators_4": "0",
            "lateral_rotators_5": "0",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            },
            {
            "patient_id": "U0005",
            "ms_acting_on_joint": "test",
            "flexors_0": "0",
            "flexors_1": "1",
            "flexors_2": "0",
            "flexors_3": "0",
            "flexors_4": "0",
            "flexors_5": "0",
            "extensors_0": "1",
            "extensors_1": "0",
            "extensors_2": "0",
            "extensors_3": "0",
            "extensors_4": "0",
            "extensors_5": "0",
            "abductors_0": "1",
            "abductors_1": "0",
            "abductors_2": "0",
            "abductors_3": "0",
            "abductors_4": "0",
            "abductors_5": "0",
            "adductors_0": "1",
            "adductors_1": "0",
            "adductors_2": "0",
            "adductors_3": "0",
            "adductors_4": "0",
            "adductors_5": "0",
            "medial_rotators_0": "0",
            "medial_rotators_1": "1",
            "medial_rotators_2": "0",
            "medial_rotators_3": "0",
            "medial_rotators_4": "0",
            "medial_rotators_5": "0",
            "lateral_rotators_0": "0",
            "lateral_rotators_1": "0",
            "lateral_rotators_2": "1",
            "lateral_rotators_3": "0",
            "lateral_rotators_4": "0",
            "lateral_rotators_5": "0",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            }
            ],
            "patient_physiotherapy_musculo_4_4and5": [
            {
            "patient_id": "U0004",
            "muscle_tone": "test",
            "other_investigation": "test",
            "skin_conditions": "0",
            "heart_disease": "1",
            "diabetes": "0",
            "osteoporosis": "1",
            "joint_replacements": "0",
            "pregnancy": "0",
            "pacemaker": "1",
            "stroke": "0",
            "rapid_weight_loss": "1",
            "bowelbladder_problems": "0",
            "malignancy": "0",
            "arthritis": "1",
            "numbness": "1",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            },
            {
            "patient_id": "U0005",
            "muscle_tone": "test",
            "other_investigation": "test",
            "skin_conditions": "0",
            "heart_disease": "1",
            "diabetes": "0",
            "osteoporosis": "1",
            "joint_replacements": "0",
            "pregnancy": "0",
            "pacemaker": "1",
            "stroke": "0",
            "rapid_weight_loss": "1",
            "bowelbladder_problems": "0",
            "malignancy": "0",
            "arthritis": "1",
            "numbness": "1",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            }
            ],
            "patient_physiotherapy_neuro_general": [
            {
            "patient_id": "U0004",
            "diagnosis": "test",
            "relevant": "test",
            "history": "test test test",
            "pre_mobid_status_community": "0",
            "pre_mobid_status_home_bound": "1",
            "pre_mobid_status_wheel_chair_bound": "0",
            "pre_mobid_status_bed_bound": "0",
            "smoking_history_start": "test",
            "smoking_history_stop": "test",
            "mental_status": "test",
            "vision": "test",
            "hearing": "test",
            "speech_swallowing": "test",
            "orientation_time": "0",
            "orientation_place": "1",
            "orientation_person": "0",
            "obey_ommands": "yes",
            "follow_gestures": "test",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            },
            {
            "patient_id": "U0005",
            "diagnosis": "test",
            "relevant": "test",
            "history": "test test test",
            "pre_mobid_status_community": "0",
            "pre_mobid_status_home_bound": "1",
            "pre_mobid_status_wheel_chair_bound": "0",
            "pre_mobid_status_bed_bound": "0",
            "smoking_history_start": "test",
            "smoking_history_stop": "test",
            "mental_status": "test",
            "vision": "test",
            "hearing": "test",
            "speech_swallowing": "test",
            "orientation_time": "0",
            "orientation_place": "1",
            "orientation_person": "0",
            "obey_ommands": "yes",
            "follow_gestures": "test",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            }
            ],
            "patient_physiotherapy_neuro_limb": [
            {
            "patients_id": "U0004",
            "shoulder_flexor_right": "test",
            "shoulder_flexor_left": "test",
            "shoulder_extensor_left": "test",
            "shoulder_extensor_right": "test",
            "shoulder_abductor_left": "test",
            "shoulder_abductor_right": "test",
            "elbow_flexor_left": "test",
            "elbow_flexor_right": "test",
            "elbow_extensor_left": "test",
            "elbow_extensor_right": "test",
            "gripping_left": "test",
            "gripping_right": "tes",
            "hip_flexor_left": "test",
            "hip_flexor_right": "test",
            "hip_extensor_left": "test",
            "hip_extensor_right": "test",
            "hip_abductor_left": "test",
            "hip_abductor_right": "test",
            "knee_flexion_left": "test",
            "knee_flexion_right": "test",
            "knee_extension_left": "test",
            "knee_extension_right": "test",
            "ankle_dorsiflexion_left": "test",
            "ankle_dorsiflexion_right": "test",
            "ankle_plantarflexion_left": "test",
            "ankle_plantarflexion_right": "test",
            "rom": "test",
            "tone": "test",
            "sensation": "test",
            "joint_position_sense": "test",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            },
            {
            "patients_id": "U0005",
            "shoulder_flexor_right": "test",
            "shoulder_flexor_left": "test",
            "shoulder_extensor_left": "test",
            "shoulder_extensor_right": "test",
            "shoulder_abductor_left": "test",
            "shoulder_abductor_right": "test",
            "elbow_flexor_left": "test",
            "elbow_flexor_right": "test",
            "elbow_extensor_left": "test",
            "elbow_extensor_right": "test",
            "gripping_left": "test",
            "gripping_right": "tes",
            "hip_flexor_left": "test",
            "hip_flexor_right": "test",
            "hip_extensor_left": "test",
            "hip_extensor_right": "test",
            "hip_abductor_left": "test",
            "hip_abductor_right": "test",
            "knee_flexion_left": "test",
            "knee_flexion_right": "test",
            "knee_extension_left": "test",
            "knee_extension_right": "test",
            "ankle_dorsiflexion_left": "test",
            "ankle_dorsiflexion_right": "test",
            "ankle_plantarflexion_left": "test",
            "ankle_plantarflexion_right": "test",
            "rom": "test",
            "tone": "test",
            "sensation": "test",
            "joint_position_sense": "test",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            }
            ],
            "patient_physiotherapy_neuro_functional_performance1": [
            {
            "patient_id": "U0004",
            "rolling_i": "0",
            "rolling_s": "1",
            "rolling_min": "0",
            "rolling_mod": "0",
            "rolling_max": "0",
            "rolling_u": "0",
            "rolling_nt": "0",
            "supine_lying_sitting_i": "0",
            "supine_lying_sitting_s": "0",
            "supine_lying_sitting_min": "1",
            "supine_lying_sitting_mod": "0",
            "supine_lying_sitting_max": "0",
            "supine_lying_sitting_u": "0",
            "supine_lying_sitting_nt": "0",
            "transfer_bed_chair_i": "1",
            "transfer_bed_chair_s": "0",
            "transfer_bed_chair_min": "0",
            "transfer_bed_chair_mod": "0",
            "transfer_bed_chair_max": "0",
            "transfer_bed_chair_u": "0",
            "transfer_bed_chair_nt": "0",
            "sit_stand_i": "0",
            "sit_stand_s": "1",
            "sit_stand_min": "0",
            "sit_stand_mod": "0",
            "sit_stand_max": "0",
            "sit_stand_u": "0",
            "sit_stand_nt": "0",
            "ambulation_i": "1",
            "ambulation_s": "0",
            "ambulation_min": "0",
            "ambulation_mod": "0",
            "ambulation_max": "0",
            "ambulation_u": "0",
            "ambulation_nt": "0",
            "rolling_comment": "test test test test",
            "spine_lying_sitting_comment": "test test test test",
            "transfer_bed_chair_comment": "test test test test",
            "sit_stand_comment": "test test test test",
            "ambulation_comment": "test test test test test",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            },
            {
            "patient_id": "U0005",
            "rolling_i": "0",
            "rolling_s": "1",
            "rolling_min": "0",
            "rolling_mod": "0",
            "rolling_max": "0",
            "rolling_u": "0",
            "rolling_nt": "0",
            "supine_lying_sitting_i": "0",
            "supine_lying_sitting_s": "0",
            "supine_lying_sitting_min": "1",
            "supine_lying_sitting_mod": "0",
            "supine_lying_sitting_max": "0",
            "supine_lying_sitting_u": "0",
            "supine_lying_sitting_nt": "0",
            "transfer_bed_chair_i": "1",
            "transfer_bed_chair_s": "0",
            "transfer_bed_chair_min": "0",
            "transfer_bed_chair_mod": "0",
            "transfer_bed_chair_max": "0",
            "transfer_bed_chair_u": "0",
            "transfer_bed_chair_nt": "0",
            "sit_stand_i": "0",
            "sit_stand_s": "1",
            "sit_stand_min": "0",
            "sit_stand_mod": "0",
            "sit_stand_max": "0",
            "sit_stand_u": "0",
            "sit_stand_nt": "0",
            "ambulation_i": "1",
            "ambulation_s": "0",
            "ambulation_min": "0",
            "ambulation_mod": "0",
            "ambulation_max": "0",
            "ambulation_u": "0",
            "ambulation_nt": "0",
            "rolling_comment": "test test test test",
            "spine_lying_sitting_comment": "test test test test",
            "transfer_bed_chair_comment": "test test test test",
            "sit_stand_comment": "test test test test",
            "ambulation_comment": "test test test test test",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            }
            ],
            "patient_physiotherapy_neuro_functional_performance2": [
            {
            "patient_id": "U0004",
            "walking_aid": "0",
            "ws": "1",
            "qs": "1",
            "wf": "0",
            "handroid": "0",
            "reciprocal_yes": "1",
            "reciprocal_no": "0",
            "rail_nil": "1",
            "rail_1": "0",
            "rail_2": "0",
            "writing_i": "1",
            "writing_s": "0",
            "writing_min": "0",
            "writing_mod": "0",
            "writing_max": "0",
            "writing_u": "0",
            "writing_nt": "0",
            "writing_comment": "test test test test",
            "holding_i": "0",
            "holding_s": "1",
            "holding_min": "0",
            "holding_mod": "0",
            "holding_max": "0",
            "holding_u": "0",
            "holding_nt": "0",
            "holding_comment": "test test test",
            "picking_up_i": "0",
            "picing_up_s": "0",
            "picking_up_min": "0",
            "picking_up_mod": "1",
            "picking_up_max": "0",
            "picking_up_u": "0",
            "picking_up_nt": "0",
            "picking_up_comment": "test test test",
            "reaching_i": "0",
            "reaching_s": "0",
            "reaching_min": "0",
            "reaching_mod": "0",
            "reaching_max": "1",
            "reaching_u": "0",
            "reaching_nt": "0",
            "reaching_comment": "test test test test test",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            },
            {
            "patient_id": "U0005",
            "walking_aid": "0",
            "ws": "1",
            "qs": "1",
            "wf": "0",
            "handroid": "0",
            "reciprocal_yes": "1",
            "reciprocal_no": "0",
            "rail_nil": "1",
            "rail_1": "0",
            "rail_2": "0",
            "writing_i": "1",
            "writing_s": "0",
            "writing_min": "0",
            "writing_mod": "0",
            "writing_max": "0",
            "writing_u": "0",
            "writing_nt": "0",
            "writing_comment": "test test test test",
            "holding_i": "0",
            "holding_s": "1",
            "holding_min": "0",
            "holding_mod": "0",
            "holding_max": "0",
            "holding_u": "0",
            "holding_nt": "0",
            "holding_comment": "test test test",
            "picking_up_i": "0",
            "picing_up_s": "0",
            "picking_up_min": "0",
            "picking_up_mod": "1",
            "picking_up_max": "0",
            "picking_up_u": "0",
            "picking_up_nt": "0",
            "picking_up_comment": "test test test",
            "reaching_i": "0",
            "reaching_s": "0",
            "reaching_min": "0",
            "reaching_mod": "0",
            "reaching_max": "1",
            "reaching_u": "0",
            "reaching_nt": "0",
            "reaching_comment": "test test test test test",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            }
            ],
            "patient_physiotherapy_neuro_functional_performance3": [
            {
            "patient_id": "U0004",
            "static_sitting_good": "0",
            "static_sitting_fair": "0",
            "static_sitting_poor": "1",
            "static_sitting_nt": "0",
            "static_sitting_comment": "test test test",
            "dynamic_sitting_good": "1",
            "dynamic_sitting_fair": "0",
            "dynamic_sitting_poor": "0",
            "dynamic_sitting_nt": "0",
            "dynamic_sitting_comment": "test test test",
            "static_standing_good": "0",
            "static_standing_fair": "0",
            "static_standing_poor": "0",
            "static_standing_nt": "1",
            "static_standing_comment": "test test test test",
            "dynamic_standing_good": "1",
            "dynamic_standing_fair": "0",
            "dynamic_standing_poor": "0",
            "dynamic_standing_nt": "0",
            "dynamic_standing_comment": "test test test test test",
            "activity_tolerance_good": "0",
            "activity_tolerance_fair": "1",
            "activity_tolerance_poor": "0",
            "activity_tolerance_nt": "0",
            "activity_tolerance_comment": "test test test",
            "short_term_goal": "test test",
            "long_term_goal": "test test",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            },
            {
            "patient_id": "U0005",
            "static_sitting_good": "0",
            "static_sitting_fair": "0",
            "static_sitting_poor": "1",
            "static_sitting_nt": "0",
            "static_sitting_comment": "test test test",
            "dynamic_sitting_good": "1",
            "dynamic_sitting_fair": "0",
            "dynamic_sitting_poor": "0",
            "dynamic_sitting_nt": "0",
            "dynamic_sitting_comment": "test test test",
            "static_standing_good": "0",
            "static_standing_fair": "0",
            "static_standing_poor": "0",
            "static_standing_nt": "1",
            "static_standing_comment": "test test test test",
            "dynamic_standing_good": "1",
            "dynamic_standing_fair": "0",
            "dynamic_standing_poor": "0",
            "dynamic_standing_nt": "0",
            "dynamic_standing_comment": "test test test test test",
            "activity_tolerance_good": "0",
            "activity_tolerance_fair": "1",
            "activity_tolerance_poor": "0",
            "activity_tolerance_nt": "0",
            "activity_tolerance_comment": "test test test",
            "short_term_goal": "test test",
            "long_term_goal": "test test",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            }
            ],
            "products": [
            {
            "id": "U0000000000010",
            "product_category_id": "1",
            "product_name": "test1",
            "price": "4000",
            "description": "test test test",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "2016-10-06 13:25:03",
            "updated_at": "2016-10-06 13:25:03",
            "deleted_at": ""
            },
            {
            "id": "U0000000000013",
            "product_category_id": "1",
            "product_name": "test2",
            "price": "5000",
            "description": "test test test",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "2016-10-06 13:25:03",
            "updated_at": "2016-10-06 13:25:03",
            "deleted_at": ""
            },
            {
            "id": "U0000000000012",
            "product_category_id": "3",
            "product_name": "test3",
            "price": "5500",
            "description": "test test test",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "2016-10-06 13:25:03",
            "updated_at": "2016-10-06 13:25:03",
            "deleted_at": ""
            }
            ],
            "schedule_investigations": [
            {
            "patient_id": "U0004",
            "schedule_id": "U0001",
            "investigation_id": "8",
            "investigation_imaging_xray_id": "",
            "investigation_imaging_usg_id": "",
            "investigation_imaging_ct_id": "",
            "investigation_imaging_mri_id": "",
            "investigation_imaging_other_id": "",
            "investigation_imaging_remark": "",
            "investigation_ecg_remark": "",
            "investigation_other_remark": "",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            },
            {
            "patient_id": "U0004",
            "schedule_id": "U0001",
            "investigation_id": "10",
            "investigation_lab_remark": "test test test",
            "investigation_imaging_xray_id": "",
            "investigation_imaging_usg_id": "",
            "investigation_imaging_ct_id": "",
            "investigation_imaging_mri_id": "",
            "investigation_imaging_other_id": "",
            "investigation_imaging_remark": "",
            "investigation_ecg_remark": "",
            "investigation_other_remark": "",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            },
            {
            "patient_id": "U0004",
            "schedule_id": "U0001",
            "investigation_id": "",
            "investigation_lab_remark": "",
            "investigation_imaging_xray_id": "52",
            "investigation_imaging_usg_id": "45",
            "investigation_imaging_ct_id": "37",
            "investigation_imaging_mri_id": "25",
            "investigation_imaging_other_id": "1",
            "investigation_imaging_remark": "test test test",
            "investigation_ecg_remark": "",
            "investigation_other_remark": "",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            },
            {
            "patient_id": "U0005",
            "schedule_id": "U0002",
            "investigation_id": "8",
            "investigation_lab_remark": "test test test",
            "investigation_imaging_xray_id": "",
            "investigation_imaging_usg_id": "",
            "investigation_imaging_ct_id": "",
            "investigation_imaging_mri_id": "",
            "investigation_imaging_other_id": "",
            "investigation_imaging_remark": "",
            "investigation_ecg_remark": "",
            "investigation_other_remark": "",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            },
            {
            "patient_id": "U0005",
            "schedule_id": "U0002",
            "investigation_id": "10",
            "investigation_lab_remark": "test test test",
            "investigation_imaging_xray_id": "",
            "investigation_imaging_usg_id": "",
            "investigation_imaging_ct_id": "",
            "investigation_imaging_mri_id": "",
            "investigation_imaging_other_id": "",
            "investigation_imaging_remark": "",
            "investigation_ecg_remark": "",
            "investigation_other_remark": "",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            }
            ],
            "schedule_patient_chief_complaint": [
            {
            "id": "U0001",
            "schedule_id": "U0001",
            "patient_id": "U0002",
            "chief_complaint_comment": "",
            "duration_days": "2",
            "duration_months": "1",
            "hopi": "hopi",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "2016-10-06 09:47:41",
            "updated_at": "",
            "deleted_at": ""
            },
            {
            "id": "U0002",
            "schedule_id": "U0001",
            "patient_id": "U0001",
            "chief_complaint_comment": "",
            "duration_days": "3",
            "duration_months": "1",
            "hopi": "hopi2",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "2016-10-06 09:47:41",
            "updated_at": "",
            "deleted_at": ""
            }
            ],
            "schedule_patient_vitals": [
            {
            "id": "U0001",
            "patient_id": "U0001",
            "schedule_id": "1",
            "date": "2016-06-06",
            "time": "02:23:32",
            "blood_pressure_sbp": "1.0",
            "blood_pressure_dbp": "1.0",
            "blood_pressure_map": "1.0",
            "spo2": "1.0",
            "pulse_rate": "1.0",
            "body_temperature_farenheit": "1.0",
            "body_temperature_celsius": "1.0",
            "weight_pound": "1.0",
            "weight_kg": "1.0",
            "height_feet": "1.0",
            "height_inches": "1.0",
            "height_cm": "1.0",
            "blood_sugar": "sugar",
            "spo2_comment": "",
            "pulse_rate_comment": "",
            "blood_sugar_comment": "",
            "bmi": "1.0",
            "remark": "",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "2016-10-06 09:47:41",
            "updated_at": "",
            "deleted_at": ""
            },
            {
            "id": "U0002",
            "patient_id": "U0001",
            "schedule_id": "1",
            "date": "2016-06-06",
            "time": "02:23:32",
            "blood_pressure_sbp": "1.0",
            "blood_pressure_dbp": "1.0",
            "blood_pressure_map": "1.0",
            "spo2": "1.0",
            "pulse_rate": "1.0",
            "body_temperature_farenheit": "1.0",
            "body_temperature_celsius": "1.0",
            "weight_pound": "1.0",
            "weight_kg": "1.0",
            "height_feet": "1.0",
            "height_inches": "1.0",
            "height_cm": "1.0",
            "blood_sugar": "sugar",
            "spo2_comment": "",
            "pulse_rate_comment": "",
            "blood_sugar_comment": "",
            "bmi": "1.0",
            "remark": "",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "2016-10-06 09:47:41",
            "updated_at": "",
            "deleted_at": ""
            }
            ],
            "schedule_physical_exams_abdomen_extre_neuro": [
            {
            "id": "U0001",
            "patient_id": "U0004",
            "schedule_id": "U0001",
            "abdomen_normal": "0",
            "abdomen_abnormal": "1",
            "abdomen_tenderness": "1",
            "abdomen_distension": "1",
            "abdomen_mass": "1",
            "abdomen_hernia": "1",
            "abdomen_bowel_sound": "1",
            "abdomen_remark": "remark",
            "extre_normal": "1",
            "extre_abnormal": "1",
            "extre_edema": "1",
            "extre_varicose": "1",
            "extre_ulcer": "1",
            "extre_gangrene": "1",
            "extre_calf_tenderness": "1",
            "extre_ampulation": "1",
            "extre_remark": "1",
            "neuro_normal": "1",
            "neuro_abnormal": "1",
            "neuro_motor_weakness": "1",
            "neuro_sensory_loss": "1",
            "neuro_abnormal_movement": "1",
            "neuro_remark": "remark",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "2016-10-06 09:47:41",
            "updated_at": "",
            "deleted_at": ""
            },
            {
            "id": "U0002",
            "patient_id": "U0004",
            "schedule_id": "U0002",
            "abdomen_normal": "1",
            "abdomen_abnormal": "1",
            "abdomen_tenderness": "1",
            "abdomen_distension": "1",
            "abdomen_mass": "1",
            "abdomen_hernia": "1",
            "abdomen_bowel_sound": "1",
            "abdomen_remark": "remark",
            "extre_normal": "1",
            "extre_abnormal": "1",
            "extre_edema": "1",
            "extre_varicose": "1",
            "extre_ulcer": "1",
            "extre_gangrene": "1",
            "extre_calf_tenderness": "1",
            "extre_ampulation": "1",
            "extre_remark": "1",
            "neuro_normal": "1",
            "neuro_abnormal": "1",
            "neuro_motor_weakness": "1",
            "neuro_sensory_loss": "1",
            "neuro_abnormal_movement": "1",
            "neuro_remark": "remark",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "2016-10-06 09:47:41",
            "updated_at": "",
            "deleted_at": ""
            }
            ],
            "schedule_physical_exams_general_pupils_head": [
            {
            "id": "U0001",
            "patient_id": "U0004",
            "schedule_id": "U0001",
            "alert": "1",
            "unconscious": "0",
            "semiconscious": "1",
            "drowsy": "1",
            "general_remark": "general remark",
            "pupils_normal": "1",
            "pupils_abnormal": "0",
            "pupils_left_pinpoint_pupil": "1",
            "pupils_left_reactive": "1",
            "pupils_left_not_reactive": "0",
            "pupils_right_pinpoint_pupil": "1",
            "pupils_right_reactive": "1",
            "pupils_right_not_reactive": "0",
            "pupils_remark": "pupils remark",
            "head_normal": "1",
            "head_abnormal": "0",
            "head_JVD": "1",
            "head_Goiter": "1",
            "head_Lympha": "1",
            "head_remark": "head remark",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "2016-10-06 09:47:41",
            "updated_at": "",
            "deleted_at": ""
            },
            {
            "id": "U0002",
            "patient_id": "U0004",
            "schedule_id": "U0002",
            "alert": "1",
            "unconscious": "0",
            "semiconscious": "1",
            "drowsy": "1",
            "general_remark": "general remark",
            "pupils_normal": "1",
            "pupils_abnormal": "0",
            "pupils_left_pinpoint_pupil": "1",
            "pupils_left_reactive": "1",
            "pupils_left_not_reactive": "0",
            "pupils_right_pinpoint_pupil": "1",
            "pupils_right_reactive": "1",
            "pupils_right_not_reactive": "0",
            "pupils_remark": "pupils remark",
            "head_normal": "1",
            "head_abnormal": "0",
            "head_JVD": "1",
            "head_Goiter": "1",
            "head_Lympha": "1",
            "head_remark": "head remark",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "2016-10-06 09:47:41",
            "updated_at": "",
            "deleted_at": ""
            }
            ],
            "schedule_physical_exams_heart_lungs": [
            {
            "id": "U0001",
            "patient_id": "U0001",
            "schedule_id": "U0001",
            "heart_normal": "1",
            "heart_abnormal": "0",
            "heart_rate_normal": "1",
            "heart_rate_brady": "1",
            "heart_rate_tachy": "0",
            "heart_rhythm_regular": "1",
            "heart_rhythm_irregular": "0",
            "heart_sound_s1": "1",
            "heart_sound_s2": "0",
            "heart_sound_systolic": "0",
            "heart_sound_diastolic": "1",
            "heart_remark": "heart remark",
            "lungs_normal": "1",
            "lungs_abnormal": "0",
            "lungs_left_chest": "1",
            "lungs_left_dullness": "0",
            "lungs_left_reduced": "1",
            "lungs_left_absent": "0",
            "lungs_left_crepitations": "1",
            "lungs_left_wheezing": "1",
            "lungs_right_chest": "0",
            "lungs_right_dullness": "0",
            "lungs_right_reduced": "1",
            "lungs_right_absent": "0",
            "lungs_right_crepitations": "1",
            "lungs_right_wheezing": "0",
            "lungs_remark": "1",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "2016-10-06 09:47:41",
            "updated_at": "",
            "deleted_at": ""
            },
            {
            "id": "U0002",
            "patient_id": "U0004",
            "schedule_id": "U0002",
            "heart_normal": "1",
            "heart_abnormal": "0",
            "heart_rate_normal": "1",
            "heart_rate_brady": "1",
            "heart_rate_tachy": "0",
            "heart_rhythm_regular": "1",
            "heart_rhythm_irregular": "0",
            "heart_sound_s1": "1",
            "heart_sound_s2": "0",
            "heart_sound_systolic": "0",
            "heart_sound_diastolic": "1",
            "heart_remark": "heart remark",
            "lungs_normal": "1",
            "lungs_abnormal": "0",
            "lungs_left_chest": "1",
            "lungs_left_dullness": "0",
            "lungs_left_reduced": "1",
            "lungs_left_absent": "0",
            "lungs_left_crepitations": "1",
            "lungs_left_wheezing": "1",
            "lungs_right_chest": "0",
            "lungs_right_dullness": "0",
            "lungs_right_reduced": "1",
            "lungs_right_absent": "0",
            "lungs_right_crepitations": "1",
            "lungs_right_wheezing": "0",
            "lungs_remark": "1",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "2016-10-06 09:47:41",
            "updated_at": "",
            "deleted_at": ""
            }
            ],
            "schedule_physiotherapy_neuro": [
            {
            "id": "U0012",
            "patient_id": "U0006",
            "schedules_id": "U00150",
            "diagnosis": "test test test",
            "resting_bp": "test",
            "resting_hr": "test",
            "resting_spo2": "test",
            "passive_rom_exercise": "0",
            "visual_exercise": "1",
            "oral_motor_exercise": "1",
            "active_assisted_rom_exercise": "0",
            "bridging_inner_range": "0",
            "transfer_bed": "0",
            "sitting_balance": "1",
            "sit_to_stand": "0",
            "standing_balance": "1",
            "stepping": "0",
            "single_leg_balance": "0",
            "march_on_spot": "0",
            "ambulation_parallel_bar": "0",
            "ambulation_walk": "1",
            "ambulation_outdoor": "0",
            "ambulation_tandem_walk": "1",
            "stair": "0",
            "arm_pedal": "1",
            "treadmill": "0",
            "hand_exercise": "0",
            "writing_assisted_exercise": "1",
            "signature_of_physiotherapist": "0",
            "remark": "test",
            "created_by": "",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            }
            ],
            "schedule_physiotherapy_musculo": [
            {
            "id": "U0015",
            "patient_id": "U0006",
            "schedules_id": "U0003",
            "ultrasound": "0",
            "hot_manager": "0",
            "traction": "1",
            "electrical_stimulation": "1",
            "infra_red": "0",
            "laser": "0",
            "exercise_therapy": "1",
            "health_education": "1",
            "others": "test",
            "signature_of_physiotherapist": "test",
            "diagnosis": "test",
            "progress_note": "test",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            }
            ],
            "schedule_provisional_diagnosis": [
            {
            "patient_id": "U0004",
            "provisional_id": "U0000000001",
            "schedule_id": "U0001",
            "remark": "test test test",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            },
            {
            "patient_id": "U0005",
            "provisional_id": "U0000000002",
            "schedule_id": "U0002",
            "remark": "test test test",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            }
            ],
            "schedule_treatment_histories": [
            {
            "id": "U0001",
            "patient_id": "U0001",
            "product_id": "U000000000001",
            "other_product": "0",
            "total_dosage": "3",
            "frequency": "3",
            "days": "2",
            "remark": "remark",
            "schedule_id": "U0001",
            "sold_dosage": "2",
            "unsold_dosage": "3",
            "time": "09:47:41",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "2016-10-06 09:47:41",
            "updated_at": "",
            "deleted_at": ""
            },
            {
            "id": "U0002",
            "patient_id": "U0002",
            "product_id": "U000000000001",
            "other_product": "0",
            "total_dosage": "2",
            "frequency": "1",
            "days": "3",
            "remark": "remark2",
            "schedule_id": "U0001",
            "sold_dosage": "3",
            "unsold_dosage": "2",
            "time": "09:47:41",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "2016-10-06 09:47:41",
            "updated_at": "",
            "deleted_at": ""
            }
            ],
            "schedule_trackings": [
            {
            "id": "U0001",
            "preparation_start_time": "test",
            "preparation_end_time": "test",
            "schedule_id": "U0001",
            "enquiry_id": "U0001",
            "arrived_to_patient_time": "test",
            "leave_from_patient_time": "test",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            },
            {
            "id": "U0002",
            "preparation_start_time": "test",
            "preparation_end_time": "test",
            "schedule_id": "U0001",
            "enquiry_id": "U0001",
            "arrived_to_patient_time": "test",
            "leave_from_patient_time": "test",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            }
            ],
            "schedules": [
            {
            "id": "U00150",
            "enquiry_id": "U00150",
            "patient_id": "U0006",
            "patient_package_id": "",
            "date": "2016-10-10",
            "time": "",
            "phone_no": "123456",
            "township_id": "1",
            "zone_id": "1",
            "car_type": "1",
            "car_type_id": "1",
            "car_type_setup_id": "1",
            "status": "new",
            "remark": "",
            "leader_id": "U0003",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": "",
            "schedule_detail": [
            {
            "schedule_id": "U00150",
            "package_id": "0",
            "service_id": "1",
            "user_id": "",
            "type": "service"
            }
            ]
            }
            ],
            "enquiries": [
            {
            "id": "U00150",
            "name": "Paing Paing",
            "nrc_no": "34345454",
            "is_new_patient": "0",
            "patient_id": "U0006",
            "patient_type_id": "0",
            "date": "2016-10-15",
            "time": "",
            "gender": "male",
            "dob": "1990-05-10",
            "phone_no": "123456",
            "address": "Yangon",
            "township_id": "1",
            "zone_id": "1",
            "case_type": "1",
            "car_type": "1",
            "car_type_id": "1",
            "enquiry1": "0",
            "enquiry2": "1",
            "enquiry3": "0",
            "enquiry4": "1",
            "having_allergy": "1",
            "status": "new",
            "remark": null,
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": "",
            "enquiry_detail": [
            {
            "enquiry_id": "U00150",
            "package_id": "0",
            "service_id": "0",
            "allergy_id": "1",
            "type": "allergy"
            }
            ]
            }
            ],
            "route": [
            {
            "id": "U001000000001",
            "name": "test1",
            "description": "test",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "2016-10-07 13:25:03",
            "updated_at": "2016-10-07 13:25:03",
            "deleted_at": ""
            },
            {
            "id": "U001000000002",
            "name": "test2",
            "description": "test",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "2016-10-06 13:25:03",
            "updated_at": "2016-10-06 13:25:03",
            "deleted_at": ""
            }
            ],
            "nutrition": [
            {
            "patient_id": "U0004",
            "schedule_id": "U0001",
            "enquiry_id": "U0001",
            "about_acceptable_weight": "0",
            "uti": "1",
            "htn_stroke_chf_cvd": "0",
            "belowaceptable_weight": "1",
            "poor_intake": "0",
            "wieght_loss": "0",
            "difficulty_swallowing": "0",
            "no_poordentition": "0",
            "clear_full_liquid": "1",
            "skin_breakthrough": "0",
            "recent_fracture_trauma": "1",
            "recent_surgery": "0",
            "edema": "0",
            "diabetes": "0",
            "rental_dieases_dialysis": "0",
            "drug_nutinteraction": "1",
            "dx_hol_nutrition": "1",
            "dx_ho_cancer": "0",
            "dx_hodehydration": "0",
            "dx_ho_dementia": "0",
            "dx_ho_mentaldx": "0",
            "other": "test test test",
            "male_nutrition_field1": "test",
            "male_nutrition_field2": "test",
            "male_nutrition_field3": "test",
            "male_nutrition_age": "test",
            "male_nutrition_field8": "test",
            "male_nutrition_field5": "test",
            "male_nutrition_field6": "test",
            "male_nutrition_field7": "test",
            "female_nutrition_field1": "test",
            "female_nutrition_field2": "test",
            "female_nutrition_field3": "test",
            "female_nutrition_age": "test",
            "female_nutrition_field8": "test",
            "female_nutrition_field5": "test",
            "female_nutrition_field6": "test",
            "female_nutrition_field7": "test",
            "protient_field1": "test",
            "protient_field2": "test",
            "protient_field3": "test",
            "fluid_field1": "test",
            "fluid_field2": "test",
            "fluid_field3": "test",
            "fluid_field4": "test",
            "fluid_field5": "test",
            "evaluation": "test",
            "plan_of_action_or_recommendation_for_care_plan": "test",
            "remark": "test",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            },
            {
            "patient_id": "U0005",
            "schedule_id": "U0002",
            "enquiry_id": "U0002",
            "about_acceptable_weight": "0",
            "uti": "1",
            "htn_stroke_chf_cvd": "0",
            "belowaceptable_weight": "1",
            "poor_intake": "0",
            "wieght_loss": "0",
            "difficulty_swallowing": "0",
            "no_poordentition": "0",
            "clear_full_liquid": "1",
            "skin_breakthrough": "0",
            "recent_fracture_trauma": "1",
            "recent_surgery": "0",
            "edema": "0",
            "diabetes": "0",
            "rental_dieases_dialysis": "0",
            "drug_nutinteraction": "1",
            "dx_hol_nutrition": "1",
            "dx_ho_cancer": "0",
            "dx_hodehydration": "0",
            "dx_ho_dementia": "0",
            "dx_ho_mentaldx": "0",
            "other": "test test test",
            "male_nutrition_field1": "test",
            "male_nutrition_field2": "test",
            "male_nutrition_field3": "test",
            "male_nutrition_age": "test",
            "male_nutrition_field8": "test",
            "male_nutrition_field5": "test",
            "male_nutrition_field6": "test",
            "male_nutrition_field7": "test",
            "female_nutrition_field1": "test",
            "female_nutrition_field2": "test",
            "female_nutrition_field3": "test",
            "female_nutrition_age": "test",
            "female_nutrition_field8": "test",
            "female_nutrition_field5": "test",
            "female_nutrition_field6": "test",
            "female_nutrition_field7": "test",
            "protient_field1": "test",
            "protient_field2": "test",
            "protient_field3": "test",
            "fluid_field1": "test",
            "fluid_field2": "test",
            "fluid_field3": "test",
            "fluid_field4": "test",
            "fluid_field5": "test",
            "evaluation": "test",
            "plan_of_action_or_recommendation_for_care_plan": "test",
            "remark": "test",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": ""
            }
            ]
            }
            ]
            }
        </pre>
    </div>
    <hr>
    <div class="row">
        <h4>Sample Output JSON</h4>
        <pre>
            {
            "aceplusStatusCode": 200,
            "aceplusStatusMessage": "Request success !",
            "tabletId": "U004",
            "user_id": "U0001",
            "max_key": [
            {
            "table_name": "invoices",
            "max_key_id": 0
            },
            {
            "table_name": "medical_history",
            "max_key_id": 0
            },
            {
            "table_name": "family_histories",
            "max_key_id": 0
            },
            {
            "table_name": "patient_family_history",
            "max_key_id": 0
            },
            {
            "table_name": "patient_family_member",
            "max_key_id": 0
            },
            {
            "table_name": "patient_medical_history",
            "max_key_id": 0
            },
            {
            "table_name": "patient_surgery_history",
            "max_key_id": 0
            },
            {
            "table_name": "products",
            "max_key_id": 0
            },
            {
            "table_name": "schedule_patient_chief_complaint",
            "max_key_id": 0
            },
            {
            "table_name": "schedule_patient_vitals",
            "max_key_id": 0
            },
            {
            "table_name": "schedule_physical_exams_abdomen_extre_neuro",
            "max_key_id": 0
            },
            {
            "table_name": "schedule_physical_exams_general_pupils_head",
            "max_key_id": 0
            },
            {
            "table_name": "schedule_physical_exams_heart_lungs",
            "max_key_id": 0
            },
            {
            "table_name": "schedule_physiotherapy_musculo",
            "max_key_id": 0
            },
            {
            "table_name": "schedule_physiotherapy_neuro",
            "max_key_id": 0
            },
            {
            "table_name": "schedule_treatment_histories",
            "max_key_id": 0
            },
            {
            "table_name": "schedule_trackings",
            "max_key_id": 0
            },
            {
            "table_name": "schedules",
            "max_key_id": 0
            },
            {
            "table_name": "enquiries",
            "max_key_id": 0
            },
            {
            "table_name": "route",
            "max_key_id": 0
            }
            ],
            "data": [
            {
            "products": [
            {
            "id": "U0000000000010",
            "product_category_id": 1,
            "product_name": "test1",
            "price": "4000.00",
            "description": "test test test",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "2016-10-06 13:25:03",
            "updated_at": "2016-10-06 13:25:03",
            "deleted_at": ""
            },
            {
            "id": "U0000000000012",
            "product_category_id": 3,
            "product_name": "test3",
            "price": "5500.00",
            "description": "test test test",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "2016-10-06 13:25:03",
            "updated_at": "2016-10-06 13:25:03",
            "deleted_at": ""
            },
            {
            "id": "U0000000000013",
            "product_category_id": 1,
            "product_name": "test2",
            "price": "5000.00",
            "description": "test test test",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "2016-10-06 13:25:03",
            "updated_at": "2016-10-06 13:25:03",
            "deleted_at": ""
            }
            ],
            "route": [
            {
            "id": "U0001",
            "name": "Route1",
            "description": "",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": "",
            "created_at": "2016-11-08 12:07:59",
            "updated_at": "2016-11-08 12:07:59",
            "deleted_at": ""
            },
            {
            "id": "U0002",
            "name": "Route2",
            "description": "",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": "",
            "created_at": "2016-11-08 12:08:13",
            "updated_at": "2016-11-08 12:08:13",
            "deleted_at": ""
            },
            {
            "id": "U001000000001",
            "name": "test1",
            "description": "test",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "2016-10-07 13:25:03",
            "updated_at": "2016-10-07 13:25:03",
            "deleted_at": ""
            },
            {
            "id": "U001000000002",
            "name": "test2",
            "description": "test",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "2016-10-06 13:25:03",
            "updated_at": "2016-10-06 13:25:03",
            "deleted_at": ""
            }
            ],
            "medical_history": [
            {
            "id": "0",
            "name": "MH-4",
            "description": "test",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": "",
            "created_at": "2016-11-13 11:27:21",
            "updated_at": "2016-11-13 11:27:21",
            "deleted_at": ""
            },
            {
            "id": "U0001",
            "name": "test1",
            "description": "test1 test1 test1 test1",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": "",
            "created_at": "2016-10-04 13:25:03",
            "updated_at": "2016-10-04 13:25:03",
            "deleted_at": ""
            },
            {
            "id": "U0002",
            "name": "test2",
            "description": "test2 test2 test2 test2",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": "",
            "created_at": "2016-10-04 13:25:03",
            "updated_at": "2016-10-04 13:25:03",
            "deleted_at": ""
            },
            {
            "id": "U0003",
            "name": "MH-3",
            "description": "test",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": null,
            "created_at": "2016-11-13 11:27:11",
            "updated_at": "2016-11-13 11:27:11",
            "deleted_at": ""
            },
            {
            "id": "U0004",
            "name": "MH-4",
            "description": "test",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": null,
            "created_at": "2016-11-13 11:27:21",
            "updated_at": "2016-11-13 11:27:21",
            "deleted_at": ""
            }
            ],
            "family_histories": [
            {
            "id": "U0001",
            "name": "test1",
            "description": "test1 test1 test1 test1",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": "",
            "created_at": "2016-10-04 13:25:03",
            "updated_at": "2016-10-04 13:25:03",
            "deleted_at": ""
            },
            {
            "id": "U0002",
            "name": "test2",
            "description": "test2 test2 test2 test2",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": "",
            "created_at": "2016-10-04 13:25:03",
            "updated_at": "2016-10-04 13:25:03",
            "deleted_at": ""
            },
            {
            "id": "U0003",
            "name": "Breast Cancer",
            "description": "",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": "",
            "created_at": "2016-11-08 12:06:28",
            "updated_at": "2016-11-08 12:06:28",
            "deleted_at": ""
            },
            {
            "id": "U0004",
            "name": "Brain Tuma",
            "description": "",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": "",
            "created_at": "2016-11-08 12:06:39",
            "updated_at": "2016-11-08 12:06:39",
            "deleted_at": ""
            },
            {
            "id": "U0012",
            "name": "Lungs",
            "description": "null",
            "created_by": "U0002",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "2016-12-01 14:19:15",
            "updated_at": "",
            "deleted_at": ""
            }
            ],
            "enquiries": [
            {
            "id": "U00150",
            "name": "Paing Paing",
            "nrc_no": "34345454",
            "is_new_patient": 0,
            "patient_id": "U0006",
            "patient_type_id": 0,
            "date": "2016-10-15",
            "time": "",
            "gender": "male",
            "dob": "1990-05-10",
            "phone_no": "123456",
            "address": "Yangon",
            "township_id": 1,
            "zone_id": 1,
            "case_type": 1,
            "car_type": 1,
            "car_type_id": 1,
            "enquiry1": 0,
            "enquiry2": 1,
            "enquiry3": 0,
            "enquiry4": 1,
            "having_allergy": 1,
            "status": "new",
            "remark": "",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": "",
            "enquiry_detail": [
            {
            "enquiry_id": "U00150",
            "package_id": 0,
            "service_id": 0,
            "allergy_id": 1,
            "type": "allergy"
            }
            ]
            }
            ],
            "schedules": [
            {
            "id": "U00150",
            "enquiry_id": "U00150",
            "patient_id": "U0006",
            "patient_package_id": "",
            "date": "2016-10-10",
            "time": "",
            "phone_no": "123456",
            "township_id": 1,
            "zone_id": 1,
            "car_type": 1,
            "car_type_id": 0,
            "car_type_setup_id": 1,
            "status": "new",
            "remark": "",
            "leader_id": "U0003",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "",
            "updated_at": "",
            "deleted_at": "",
            "schedule_detail": [
            {
            "schedule_id": "U00150",
            "package_id": 0,
            "service_id": 1,
            "user_id": "",
            "type": "service"
            }
            ]
            }
            ],
            "schedule_treatment_histories": [],
            "patients": [],
            "patient_medical_history": [],
            "patient_family_history": [],
            "patient_surgery_history": [],
            "patient_family_member": [
            {
            "id": "U0001",
            "name": "Mother",
            "description": "",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": "",
            "created_at": "2016-11-08 12:04:52",
            "updated_at": "2016-11-08 12:04:52",
            "deleted_at": ""
            },
            {
            "id": "U0002",
            "name": "Father",
            "description": "",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": "",
            "created_at": "2016-11-08 12:05:08",
            "updated_at": "2016-11-08 12:05:08",
            "deleted_at": ""
            },
            {
            "id": "U0003",
            "name": "Brother",
            "description": "",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": "",
            "created_at": "2016-11-08 12:05:21",
            "updated_at": "2016-11-08 12:05:21",
            "deleted_at": ""
            },
            {
            "id": "U0004",
            "name": "Sister",
            "description": "",
            "created_by": "U0001",
            "updated_by": "U0001",
            "deleted_by": "",
            "created_at": "2016-11-08 12:05:35",
            "updated_at": "2016-11-08 12:05:35",
            "deleted_at": ""
            },
            {
            "id": "U001000000001",
            "name": "test1",
            "description": "Aunt",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "2016-10-04 13:25:03",
            "updated_at": "2016-10-04 13:25:03",
            "deleted_at": ""
            },
            {
            "id": "U001000000002",
            "name": "test2",
            "description": "Aunt",
            "created_by": "U0001",
            "updated_by": "",
            "deleted_by": "",
            "created_at": "2016-10-04 13:25:03",
            "updated_at": "2016-10-04 13:25:03",
            "deleted_at": ""
            }
            ]
            }
            ]
            }
        </pre>
    </div>
    <hr>
</div>
@stop

@section('page_script')

@stop