@include('layouts.partial.header_patient')
@include('layouts.partial.nav_patient')
@yield('script')
@yield('page_script')
@yield('content')
@include('layouts.partial.footer')
@include('sweet::alert')
